### ISSUE TITLE
Please comment here to add yourself as a collaborator!

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/animated-spoon#1]
_Tell us -- where are you originally from?_

**Comment by jerry-ennett** [comment]
Wisconsin Rapids

**Comment by ericlarsen13** [comment]
Cedar Falls, Iowa

**Comment by scott-larson** [comment]
Canby, Minnesota

**Comment by matt-roeckers** [comment]
Reedsburg, WI

**Comment by jrspalding** [comment]
Fremont, NE

**Comment by kevin-charpentier** [comment]
South Saint Paul, MN

**Comment by Brian-Phillippi** [comment]
Ham Lake, MN

**Comment by ryan-koshiol** [comment]
Saint Cloud, MN

**Comment by bill-kunze** [comment]
Hinckley, MN

**Comment by nate-beaudin** [comment]
Prior Lake, MN

**Comment by trash1729** [comment]
Saint Paul, MN

**Comment by jeffrey-jakubowsky** [comment]
- **Eagan, MN**

**Comment by JamesWomack-Securian** [comment]
North Saint Paul, MN

**Comment by dan-bock** [comment]
`Minnesota!`

**Comment by githubteacher** [comment]
:tada: @jerry-ennett, @ericlarsen13, @scott-larson, @matt-roeckers, @jrspalding, @kevin-charpentier, @Brian-Phillippi, @ryan-koshiol, @bill-kunze, @nate-beaudin, @trash1729, @jeffrey-jakubowsky, @JamesWomack-Securian, and @dan-bock are now  repository collaborators. :balloon:

**Comment by stoe** [comment]
hello there

**Comment by githubteacher** [comment]
:tada: @stoe is now a repository collaborator. :balloon:

**Comment by brianamarie** [comment]
hello 👋

**Comment by githubteacher** [comment]
:tada: @brianamarie is now a repository collaborator. :balloon:
